### ISSUE TITLE
Examples missing

### ISSUE THREAD

**Issue by eddysalzmann** [crowdin/crowdin-api-client-js#142]
Hi there,

is there any documentation how the client works with the API? Besides the examples in readme there is nothing to understand how to make all of the different calls...

Thank you!

**Comment by TaniaMal** [comment]
Hi @eddysalzmann!

Let me please double-check this with the team and come back to you with the updates.

Will keep you posted,

**Comment by TaniaMal** [comment]
Hi @eddysalzmann!

Sorry for the late reply!

Currently, there are no examples how the client works with the API. However, we have already passed this to the team in order to add such details to the documentation.

Hope for your understanding, but should you have another questions, we'll be happy to help :)
